name: Bold Finance
favicon: null
layout_spectrum: 0.4293942409567535
typography_spectrum: 0.8787242360413074
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.49642870388925076
  lightness: 0.5894996924325824
  saturation: 0.6917225692886859
  rhythmicContrast: 0.7191886745858938
purpose: []
